name: dart_cashmatic
description: Cashmatic SELFpay 1060
version: 1.0.0
repository: https://github.com/Marks1996/dart_cashmatic
publish_to: https://pub.flutter-io.cn/

environment:
  sdk: ">=2.19.2 <3.0.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
